services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  asset-pricing-service:
    build: ./assetpricing
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  portfolio-management-service:
    build: ./portfoliomanagement
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres
      - redis

  user-portfolio-service:
    build: ./userportfolio
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
      - redis
